### ISSUE TITLE
Composer v1 to v2 issues

### ISSUE THREAD

**Issue by alanski66** [bhashkar007/guest-entries-notification#9]
ON my local host i have this plugin installed and running ok (using composer v1)
ON my staging site server I use composer 2.
I see this issue here : https://github.com/bhashkar007/guest-entries-notification/issues/6
is meant to have resolved composer 2 issues.

Every time i go t settings page I get a 500 error: here is the debug log

Whats the solution?

ReflectionException: Class by\guestentriesnotification\assetbundles\guestentriesnotification\GuestEntriesNotificationAsset does not exist in /mypath/vendor/yiisoft/yii2/di/Container.php:508
Stack trace:
#0 /mypath/vendor/yiisoft/yii2/di/Container.php(508): ReflectionClass->__construct('by\\guestentries...')
#1 /mypath/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('by\\guestentries...')
#2 /mypath/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('by\\guestentries...', Array, Array)
#3 /mypath/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('by\\guestentries...', Array, Array)
#4 /mypath/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#5 /mypath/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('by\\guestentries...', Array, true)
#6 /mypath/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('by\\guestentries...')
#7 /mypath/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('by\\guestentries...')
#8 /mypath/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#9 /mypath/storage/runtime/compiled_templates/1a/1a6448779da4d6f2db3ba4af3f1071603432ea5ad38eff21113b1caee5b17a70.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#10 /mypath/vendor/twig/twig/src/Template.php(405): __TwigTemplate_80be7cb02ca4d456bd6abbd0dfb84743d9e781cc44a29dbb87d2a7d27d4a0343->doDisplay(Array, Array)
#11 /mypath/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /mypath/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /mypath/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /mypath/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /mypath/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('guest-entries-n...', Array)
#16 /mypath/vendor/by/guest-entries-notification/src/GuestEntriesNotification.php(113): craft\web\View->renderTemplate('guest-entries-n...', Array)
#17 /mypath/vendor/craftcms/cms/src/base/Plugin.php(217): by\guestentriesnotification\GuestEntriesNotification->settingsHtml()
#18 /mypath/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#19 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('guest-entries-n...', Object(by\guestentriesnotification\GuestEntriesNotification))
#20 /mypath/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /mypath/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /mypath/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#23 /mypath/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#24 /mypath/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#25 /mypath/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#26 /mypath/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#27 /mypath/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /mypath/public_html/index.php(21): yii\base\Application->run()
#29 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "by\guestentriesnotification\assetbundles\guestentriesnotification\GuestEntriesNotificationAsset". in /mypath/vendor/yiisoft/yii2/di/Container.php:510
Stack trace:
#0 /mypath/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('by\\guestentries...')
#1 /mypath/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('by\\guestentries...', Array, Array)
#2 /mypath/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('by\\guestentries...', Array, Array)
#3 /mypath/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#4 /mypath/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('by\\guestentries...', Array, true)
#5 /mypath/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('by\\guestentries...')
#6 /mypath/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('by\\guestentries...')
#7 /mypath/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#8 /mypath/storage/runtime/compiled_templates/1a/1a6448779da4d6f2db3ba4af3f1071603432ea5ad38eff21113b1caee5b17a70.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#9 /mypath/vendor/twig/twig/src/Template.php(405): __TwigTemplate_80be7cb02ca4d456bd6abbd0dfb84743d9e781cc44a29dbb87d2a7d27d4a0343->doDisplay(Array, Array)
#10 /mypath/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /mypath/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#12 /mypath/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /mypath/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /mypath/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('guest-entries-n...', Array)
#15 /mypath/vendor/by/guest-entries-notification/src/GuestEntriesNotification.php(113): craft\web\View->renderTemplate('guest-entries-n...', Array)
#16 /mypath/vendor/craftcms/cms/src/base/Plugin.php(217): by\guestentriesnotification\GuestEntriesNotification->settingsHtml()
#17 /mypath/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#18 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('guest-entries-n...', Object(by\guestentriesnotification\GuestEntriesNotification))
#19 /mypath/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /mypath/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#21 /mypath/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#22 /mypath/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#23 /mypath/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#24 /mypath/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#25 /mypath/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /mypath/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /mypath/public_html/index.php(21): yii\base\Application->run()
#28 {main}

**Comment by alanski66** [comment]
Mmm fixed by renaming
/by/guest-entries-notification/src/assetbundles/GuestEntriesNotification
to 
/by/guest-entries-notification/src/assetbundles/guestentriesnotification
